version: '1'
name: "test-app"
services:
  db:
   image: "postgres"
   restart: always
   container_name: test-app-db
   environment:
     POSTGRES_PASSWORD: password
     POSTGRES_USER: "postgres"
     POSTGRES_DB: "test-app"
   volumes:
     - database_data:/var/lib/postgressql-data/
   ports:
     - "9010:5432"

volumes:
  database_data: